### ISSUE TITLE
Question:  Have you tried this code with CUDA?

### ISSUE THREAD

**Issue by rtrahms** [Nebula4869/YOLOv5-LibTorch#3]
I am pursuing a similar path, and have been able to loop multiple inference calls to module::forward() when using CPU version of libtorch and PT file.  CUDA version not so much - the inference call makes it through the first time, but subsequent call results in an exception.  Have you tried this, and what are your results?  FYI I am using CUDA 10.1.

I also  logged an issue on this with pytorch group:
https://github.com/pytorch/pytorch/issues/47590

Thanks,
Rob

**Comment by rtrahms** [comment]
Thanks, I found the issue.  I rebuilt with libtorch 1.7, CUDA 11.0, and included ALL DLLs from libtorch distribution and CUDA distribution.  Worked as expected.

**Comment by DBraun** [comment]
What was the issue?
